# HTTP Server
server:
    port: 8083

spring:
    application:
        name: eureka

# Configure this Discovery Server
eureka:
    instance:
        hostname: localhost
    client:  # Not a client, don't register with yourself
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://localhost:8083/eureka/